- client/.github/pull_request_template.md
- client/.github/workflows/main.yml
This will add github action pipelines for linting and testing
* [1234](https://github.com/tapis-project/tapis-ui/issues/1234)
Add github actions
1. In this PR, github action results should be available
> 0006 - Github actions for client side tests and linting

- src/tapis-redux/__tests__/api.sagas.test.ts
- tsconfig.json
- webpack.common.js
* [TUI-1234](https://github.com/tapis-project/tapis-ui/issues/1234)
1.
> task/TUI-26 - fix webpack to ignore tests

- src/tapis-app/src/App/App.tsx
- src/tapis-ui/src/components/jobs/JobLauncher/JobLauncher.tsx
- src/tapis-ui/src/components/jobs/JobsListing/JobsListing.tsx
- src/tapis-ui/src/components/systems/SystemList/SystemList.scss
Need to fix a few small UI issues:
- Change section header for Launcher
- Remove old job launcher/listing headers
- Add cursor for SystemList
- Fix launcher route
* [TUI-69](https://github.com/tapis-project/tapis-ui/issues/69)
> Task/TUI-69 - Minor bug fixes from merging

- src/tapis-app/src/Sections/ListSection/ListSection.tsx
- src/tapis-redux/src/index.ts
- src/tapis-redux/src/utils/index.ts
- src/tapis-redux/src/utils/token.ts
Token login checks
- ListSection redirects to login if token is expired or nonexistent
- isExpired utility function in tapis-redux/utils
1. Be logged out
2. Try accessing /apps - you should be redirected to /login
3. Log in
4. Try accessing /apps - it should work fine
> task/TUI-75 -- handle login timeouts

- src/tapis-ui/src/components/apps/AppsListing/AppsListing.tsx
- src/tapis-ui/src/components/files/FileListing/FileListing.tsx
- src/tapis-ui/src/components/jobs/JobsListing/JobsListing.tsx
- src/tapis-ui/src/components/systems/SystemList/SystemList.tsx
Fix "missing key" errors in listing components
Just needed to add a unique key for each listing
1. Login
2. Check all of the listings (Systems, Files, Apps, Jobs)
> task/TUI-75 - Error messages in listings

- src/tapis-app/src/App/App.scss
- src/tapis-app/src/Sections/Apps/Apps.tsx
- src/tapis-app/src/Sections/Jobs/Jobs.tsx
- src/tapis-app/src/Sections/Systems/Systems.tsx
- src/tapis-ui/src/components/systems/SystemList/SystemList.tsx
Add refresh button for listing areas.
1. Got to Systems, Apps, Jobs
2. Select a system, app, or job
3. Click refresh button
> task/TUI-75 - listing refresh button

- src/tapis-hooks/src/context/TapisContext.tsx
- src/tapis-hooks/src/context/useTapisConfig.ts
- src/tapis-hooks/src/provider/TapisProvider.tsx
* [TUI-1234](https://github.com/tapis-project/tapis-ui/issues/1234)
1.
> React-query: Use a query as the source of truth for access tokens.

- src/tapis-api/jobs/details.ts
- src/tapis-api/jobs/index.ts
- src/tapis-api/jobs/list.ts
- src/tapis-app/Sections/Apps/Apps.tsx
- src/tapis-app/Sections/Dashboard/Dashboard.tsx
- src/tapis-app/Sections/Jobs/Jobs.tsx
- src/tapis-hooks/jobs/index.ts
- src/tapis-hooks/jobs/queryKeys.ts
- src/tapis-hooks/jobs/useDetails.ts
- src/tapis-hooks/jobs/useList.ts
- src/tapis-ui/components/jobs/JobDetail/JobDetail.tsx
- src/tapis-ui/components/jobs/JobsListing/JobsListing.test.tsx
- src/tapis-ui/components/jobs/JobsListing/JobsListing.tsx
- src/tapis-ui/components/jobs/JobsListing/index.ts
Support Jobs listing and details in react-query
* [TUI-105](https://github.com/tapis-project/tapis-ui/issues/105)
- Added tapis-api/jobs listing and details
- Added tapis-hooks/jobs useList and useDetails
- JobDetail and JobListing use hooks
- Dashboard updated to use hooks
1. npm start
2. Log in as cicsvc
3. Look at jobs listings in dashboard and jobs area
4. Select a job to view its details
> task/TUI-105 -- jobs list react query

- src/tapis-api/files/index.ts
- src/tapis-api/files/list.ts
- src/tapis-hooks/files/index.ts
- src/tapis-hooks/files/queryKeys.ts
- src/tapis-hooks/files/useList.ts
- src/tapis-hooks/utils/concatResults.ts
- src/tapis-ui/components/files/FileListing/FileListing.test.tsx
- src/tapis-ui/components/files/FileListing/FileListing.tsx
InfiniteQuery hook for file listings
* [TUI-103](https://github.com/tapis-project/tapis-ui/issues/103)
- tapis-api/files
- tapis-hooks/files
- FileListing component updated to use react-query hooks
1. npm test
2. npm start
3. Log in with cicsvc service account
4. Browse to a system and retrieve a file listing
> task/TUI-103 -- Files Listing hooks

- src/tapis-api/jobs/submit.ts
- src/tapis-app/Sections/Apps/Apps.tsx
- src/tapis-hooks/jobs/queryKeys.ts
- src/tapis-hooks/jobs/useSubmit.ts
- src/tapis-ui/components/jobs/JobLauncher/JobLauncher.test.tsx
- src/tapis-ui/components/jobs/JobLauncher/JobLauncher.tsx
* [TUI-1234](https://github.com/tapis-project/tapis-ui/issues/1234)
1.
> React query usemutation proposal

- package-lock.json
- package.json
Restore gh-pages scripts with recommended "homepages" setting, as per CRA docs
1.
> Restore gh-pages scripts

- src/index.tsx
- src/tapis-app/index.css
> Move bootstrap import to index.css to prevent clobbering on build

- package-lock.json
- package.json
- src/tapis-ui/_common/FieldWrapper/FieldWrapper.tsx
- src/tapis-ui/_common/Form/FileInputDropZoneFormField.js
- src/tapis-ui/_common/Form/index.js
- src/tapis-ui/components/authenticator/Login/Login.tsx
- src/tapis-ui/components/jobs/JobLauncher/JobLauncher.test.tsx
- src/tapis-ui/components/jobs/JobLauncher/JobLauncher.tsx
> Replace Formik with react-hook-form

- src/tapis-app/Login/_Layout/Layout.tsx
> Redirect users to their original intended destination after login

- src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
- src/tapis-ui/components/jobs/JobLauncher/FileInputs.tsx
No generics for FieldArray, but add type safety to FileInputs (with proper error extraction.)
1.
> Error extraction with type safety

- src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
- src/tapis-ui/components/jobs/JobLauncher/FileInputs.tsx
> Type coercion to have item type generic

- src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
> alternate generic type setup for FieldArray

- package-lock.json
- src/fixtures/jobs.fixtures.ts
Provide passing and failing job fixtures
- [TUI-116](https://github.com/tapis-project/tapis-ui/issues/116)
Added 2 passing and 1 failing job fixtures to src/fixtures/jobs.fixtures.ts
> Provide passing and failing job fixtures

- src/tapis-app/Dashboard/_components/Dashboard/Dashboard.tsx
Add a dashboard card for files
- [TUI-239](https://github.com/tapis-project/tapis-ui/issues/239)
1.
> Dashboard card for Files

- src/tapis-ui/components/jobs/JobLauncher/JobLauncherWizard.tsx
- src/tapis-ui/components/jobs/JobLauncher/steps/ArchiveFilter.module.scss
- src/tapis-ui/components/jobs/JobLauncher/steps/ArchiveFilter.tsx
> Task/t UI 286  archive filter

- src/tapis-ui/components/jobs/JobLauncher/FieldArray.module.scss
- src/tapis-ui/components/jobs/JobLauncher/JobLauncherWizard.tsx
- src/tapis-ui/components/jobs/JobLauncher/components/FormikJobStepWrapper.tsx
- src/tapis-ui/components/jobs/JobLauncher/steps/ArchiveFilter.module.scss
- src/tapis-ui/components/jobs/JobLauncher/steps/ArchiveFilter.tsx
- src/tapis-ui/components/jobs/JobLauncher/steps/EnvVariables.tsx
- src/tapis-ui/components/jobs/JobLauncher/steps/FileInputArrays.tsx
- src/tapis-ui/components/jobs/JobLauncher/steps/FileInputs.tsx
Environment variables parameterSet
- [TUI-288](https://github.com/tapis-project/tapis-ui/issues/288)
- Add environment variables parameterset
- FormikJobStepWrapper merges parameterSet to prevent overwriting other parameters
- Refactor styles
- Use h3 for step titles
1. Add and remove environment variables
> task/TUI-288 - environment variables

- src/tapis-ui/_common/FieldWrapperFormik/FieldWrapperFormik.tsx
- src/tapis-ui/components/jobs/JobLauncher/steps/FileInputArrays.tsx
- Fix file selection modal issues in FileInputArrays step
- Fix Formik rendering of errors
- [TUI-316](https://github.com/tapis-project/tapis-ui/issues/316)
1.
> task/TUI-316 -- bug fixes

- package-lock.json
- package.json
- src/tapis-api/jobs/cancel.ts
- src/tapis-api/jobs/index.ts
- src/tapis-app/Jobs/JobDetail/_Layout/Layout.tsx
- src/tapis-app/Jobs/_components/JobsToolbar/JobsToolbar.module.scss
- src/tapis-app/Jobs/_components/JobsToolbar/JobsToolbar.tsx
- src/tapis-app/Jobs/_components/JobsToolbar/index.ts
- src/tapis-app/Jobs/_components/index.ts
- src/tapis-hooks/jobs/index.ts
- src/tapis-hooks/jobs/queryKeys.ts
- src/tapis-hooks/jobs/useCancel.ts
- src/tapis-ui/_common/ConfirmModal/ConfirmModal.tsx
- src/tapis-ui/_common/ConfirmModal/index.js
- src/tapis-ui/_common/index.js
- src/tapis-ui/components/jobs/JobDetail/JobDetail.tsx
Added the confirm modal.
Added the ability to cancel Jobs.
- Fixed the bug that would crash the site given a bad job UUID request
1.
> Adding Confirm Modal and Cancel Job Utility

- src/tapis-api/systems/index.ts
- src/tapis-api/systems/shareSystemPublic.ts
- src/tapis-api/systems/unShareSystemPublic.ts
- src/tapis-app/Systems/SystemDetail/_Layout/Layout.tsx
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/ShareSystemPublicModal/ShareSystemPublicModal.module.scss
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/ShareSystemPublicModal/ShareSystemPublicModal.tsx
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/ShareSystemPublicModal/index.ts
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/SystemLayoutToolbar.module.scss
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/SystemLayoutToolbar.tsx
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/UnShareSystemPublicModal/UnShareSystemPublicModal.module.scss
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/UnShareSystemPublicModal/UnShareSystemPublicModal.tsx
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/UnShareSystemPublicModal/index.ts
- src/tapis-app/Systems/SystemDetail/_Layout/SystemLayoutToolbar/index.ts
- src/tapis-hooks/systems/index.ts
- src/tapis-hooks/systems/queryKeys.ts
- src/tapis-hooks/systems/useShareSystemPublic.ts
- src/tapis-hooks/systems/useUnShareSystemPublic.ts
> Added Share and Unshare System Publicly Feature

- src/tapis-app/_Router/Router.tsx
- src/tapis-app/_components/Sidebar/Sidebar.tsx
- [TUI-351](https://github.com/tapis-project/tapis-ui/issues/351)
1.
> Added ML Hub to sidebar and router link

- src/tapis-app/MlHub/Models/ModelDetails.module.scss
- src/tapis-app/MlHub/Models/ModelDetails.tsx
- src/tapis-app/MlHub/Models/Models.tsx
- src/tapis-app/MlHub/Models/_Router/Router.tsx
- src/tapis-app/MlHub/Models/index.ts
- src/tapis-app/MlHub/_Router/Router.tsx
- src/tapis-hooks/ml-hub/models/basePath.ts
https://github.com/tapis-project/tapis-ui/assets/170014805/e35c55d5-d205-4b6e-83a2-51c9f52e08d3
1.
> Task/t UI 367  single model info and button placements

- package-lock.json
- package.json
- src/tapis-app/MlHub/Models/ModelDetails.tsx
- src/tapis-hooks/ml-hub/models/basePath.ts
- src/tapis-ui/_common/JSONDisplay/JSONDisplay.tsx
> Task/t UI 375  single model page model card functionality

- packages/tapisui-hooks/src/ml-hub/models/index.ts
- packages/tapisui-hooks/src/ml-hub/models/queryKeys.ts
- packages/tapisui-hooks/src/ml-hub/models/useModelCardDetails.ts
- src/app/MlHub/Models/ModelDetails.tsx
> Adding queryKeys for models

- src/app/MlHub/Models/ModelDetails.module.scss
- src/app/MlHub/Models/ModelDetails.tsx
> add markdwn, add SCSS, add modal style

- .github/workflows/main.yml
- src/app/Jobs/_components/JobsToolbar/JobsToolbar.tsx
> Bugfix/t UI 357 cancel job button

- packages/tapisui-common/src/ui-formik/FieldWrapperFormik/fields/FormikTapisFile.tsx
- [TUI-343](https://github.com/tapis-project/tapis-ui/issues/343)
1.
> Bugfix/t UI 343 forward slash missing source url

- src/app/MlHub/_components/SearchBar/SearchBar.module.scss
- src/app/MlHub/_components/SearchBar/SearchBar.tsx
> Searchbar styling

- src/app/Apps/_Layout/Layout.tsx
- src/app/Apps/_components/AppsToolbar/AppsToolbar.module.scss
- src/app/Apps/_components/AppsToolbar/AppsToolbar.tsx
- src/app/Files/_Layout/Layout.module.scss
- src/app/Files/_Layout/Layout.tsx
- src/app/Jobs/_Layout/Layout.module.scss
- src/app/Jobs/_Layout/Layout.tsx
- src/app/Systems/_components/SystemToolbar/SystemToolbar.tsx
- src/app/_components/Help/AppsHelp/AppsHelp.tsx
- src/app/_components/Help/AppsHelp/index.ts
- src/app/_components/Help/FilesHelp/FilesHelp.tsx
- src/app/_components/Help/FilesHelp/index.ts
> Task/t UI 411 mixed page headers

- src/app/Systems/_components/SystemToolbar/CreateSystemModal/CreateSystemModal.tsx
- src/app/Systems/_components/SystemToolbar/CreateSystemModal/Settings/AdvancedSettings.tsx
> Bugfix/t UI 433 system fields when can exec false

- src/app/Systems/_components/SystemsNav/SystemsNav.tsx
> Task/t UI 444 view disabled systems definitions

- src/app/Dashboard/_components/Dashboard/Dashboard.tsx
> fix systems limit. Systems and Files now reflect the current amount of systems in creation.
