tapis-project/tapis-ui

src/tapis-app/src/Sections/ListSection/ListSection.tsx

When token expires, force logout. (Expired tokens redirect to login but sidebar state did not reflect being "logged out")
1.

Hotfix: force logout if token is expired

---

src/tapis-app/src/Sections/Apps/Apps.tsx

Reset job submission status when selecting a different app
Dispatch resetSubmit when selecting an app in the Apps section
1. Log in as cicsvc
2. Launch the sleepseconds.app.demo app
3. Select a different app
4. The job submission status and messages should reset

Reset submit status when selecting a different app

---

src/tapis-ui/src/components/apps/AppsListing/AppsListing.tsx
src/tapis-ui/src/components/jobs/JobsListing/JobsListing.tsx

Empty list messages
Add "No x found" when visiting a list that is empty (jobs, apps). Jobs currently displays an error due to a TAPIS side issue
1.

Empty list messages

---

src/tapis-app/__tests__/Sidebar.test.tsx
src/tapis-app/src/Sections/Dashboard/Dashboard.tsx
src/tapis-app/src/Sidebar/Sidebar.tsx

Sidebar and Dashboard read `useTapisConfig` accessToken
closes #101 
* [TUI-101](https://github.com/tapis-project/tapis-ui/issues/101)
1. Log in
2. Sidebar should show logged in nav items

task/TUI-101 - dashboard react query

---

src/tapis-api/apps/index.ts
src/tapis-api/apps/list.ts
src/tapis-app/Sections/Apps/Apps.tsx
src/tapis-app/Sections/Dashboard/Dashboard.tsx
src/tapis-hooks/apps/index.ts
src/tapis-hooks/apps/queryKeys.ts
src/tapis-hooks/apps/useList.ts
src/tapis-ui/components/apps/AppsListing/AppsListing.test.tsx
src/tapis-ui/components/apps/AppsListing/AppsListing.tsx
src/tapis-ui/components/apps/AppsListing/index.ts

Apps listing uses tapis-hooks and react-query
* [TUI-104](https://github.com/tapis-project/tapis-ui/issues/104)
- Added tapis-api/apps
- Added tapis-hooks/apps/useList
- Converted tapis-ui/AppsListing to use tapis-hooks
- Converted dashboard to use apps useList
1. npm test
2. npm start
3. Log in with cicsvc account, browse and see apps
Jobs Launcher currently does not show the selected app's execution system at this point.

task/TUI-104 -- apps list react query

---

src/tapis-api/authenticator/login.ts
src/tapis-api/jobs/index.ts
src/tapis-api/jobs/submit.ts
src/tapis-api/utils/errorDecoder.ts
src/tapis-app/Sections/Apps/Apps.tsx
src/tapis-hooks/jobs/index.ts
src/tapis-hooks/jobs/queryKeys.ts
src/tapis-hooks/jobs/useSubmit.ts
src/tapis-ui/components/jobs/JobLauncher/JobLauncher.test.tsx
src/tapis-ui/components/jobs/JobLauncher/JobLauncher.tsx

Jobs Submission uses react-query
* [TUI-106](https://github.com/tapis-project/tapis-ui/issues/106)
- tapis-api/jobs/submit
- tapis-hooks/jobs/useSubmit
- JobsLauncher uses react-query hooks
1. npm start
2. Launch a job from an application
3. Switch to a different application - job submission state should reset
4. Change the exec system to something that's not the default. Upon submission you should see an error message
5. Switch to a different application - job submission state and error should reset

task/TUI-106 - react query jobs submission

---

src/tapis-ui/components/jobs/JobLauncher/FieldArray.module.scss
src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
src/tapis-ui/components/jobs/JobLauncher/FileInputs.module.scss
src/tapis-ui/components/jobs/JobLauncher/FileInputs.tsx
src/tapis-ui/components/jobs/JobLauncher/JobLauncher.tsx

FieldArray now passes a remove callback to the rendered component
- [TUI-162](https://github.com/tapis-project/tapis-ui/issues/162)
- FieldArray passes remove callback to rendered component
- FileInputField now selectively renders a remove button based on meta.required and if remove callback is present
- FileInputs inputs property renamed to appInputs to better reflect where the source FileInput definitions are coming from
1. Add a file input to a job launch
2. make sure required ones are not removable
3. make sure added fileinputs are removable

task/TUI-162 - Move remove button display concern to rendered component

---

src/tapis-ui/components/jobs/JobLauncher/FileInputs.tsx
src/tapis-ui/components/jobs/JobLauncher/JobLauncher.tsx

Apps use the `FileInput` type, while Jobs uses `InputSpec`. Due to existing type discrepancies now and future type changes, apps FileInputs needs to be mapped to jobs InputSpecs.
- [TUI-159](https://github.com/tapis-project/tapis-ui/issues/159)
- Added mapping function from app file inputs to job input specs
- JobLauncher now uses a defaultValue structure
- FileInputs and FileInputFields use correct `InputSpec` type
1.

task/TUI-159 - Distinguish between apps FileInput type and jobs InputSpec type

---

src/tapis-ui/_common/Collapse/Collapse.tsx
src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
src/tapis-ui/components/jobs/JobLauncher/FileInputs.tsx

Make FileInputs FieldArray optionally collapsable.
- [TUI-164](https://github.com/tapis-project/tapis-ui/issues/164)
- Added isCollapsable flag FieldArray
- Default isCollapsable to true in FileInputs
- Render FieldArray with Collapse only if isCollapsable prop on FieldArray is true and there are required FileInputs
- Default open to true if there are required FileInputs
1. Navigate to Apps
2. Click the 'bsf2 v1' app link. Expect Collapse to be rendered and open
3. Click the SleepSeconds.app.demo v0.0.1 link. Expect Collapse not to be rendered

Add optional collapsable UI to FileInputs FieldArray

---

src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
src/tapis-ui/components/jobs/JobLauncher/FileInputs.tsx

ArrayField accepts 2 generic arguments `<TFieldValues, TArrayPath>` in line with how react-hook-form defines its own custom field types. `TFieldValues` is the overall form schema, e.g. `ReqSubmitJob` and `TArrayPath` is a string literal that describes the path to the field.

ArrayField type scheme with more idiomatic generics

---

src/index.tsx
src/tapis-app/Dashboard/_components/Dashboard/Dashboard.tsx

Add projects listing to dashboard
- [TUI-92](https://github.com/tapis-project/tapis-ui/issues/92)
- Add projects to dashboard
1. 
Dashboard link not implemented, will be implemented in further pr

TUI-92 - Streams in Dashboard

---

src/tapis-app/Files/FileListing/_Layout/Layout.tsx
src/tapis-app/Files/_Layout/Layout.tsx
src/tapis-app/Files/_Router/Router.tsx
src/tapis-app/Files/_components/FilesContext/FilesContext.tsx
src/tapis-app/Files/_components/FilesContext/FilesProvider.tsx
src/tapis-app/Files/_components/FilesContext/index.tsx
src/tapis-app/Files/_components/FilesContext/useFilesSelect.test.ts
src/tapis-app/Files/_components/FilesContext/useFilesSelect.ts
src/tapis-app/Files/_components/Toolbar/CopyMoveModal/CopyMoveModal.test.tsx
src/tapis-app/Files/_components/Toolbar/CopyMoveModal/CopyMoveModal.tsx
src/tapis-app/Files/_components/Toolbar/RenameModal/RenameModal.test.tsx
src/tapis-app/Files/_components/Toolbar/RenameModal/RenameModal.tsx
src/tapis-app/Files/_components/Toolbar/Toolbar.tsx
src/tapis-app/Files/_components/Toolbar/_components/FileExplorer/FileExplorer.tsx
src/tapis-ui/components/files/FileListing/FileListing.module.scss
src/tapis-ui/components/files/FileListing/FileListing.test.tsx
src/tapis-ui/components/files/FileListing/FileListing.tsx

Implement Select All feature for files listing
- [TUI-205](https://github.com/tapis-project/tapis-ui/issues/205)
- Implemented a select all header checkbox for tapis-ui/FilesListing
- Implemented a tapis-app level FilesListing provider and useFilesSelect hook
- tapis-ui/FilesListing selection now calls back to client and allows it to use its own file selection management (in this case useFilesSelect hook)
- Modals use unselect and clear (from useFilesSelect hook) on successful operations to clear file selections for filenames that have changed
- tapis-ui/FilesListing selection highlights
1. select files
2. Try select all/unselect all
3. Try navigation 
4. Try modals
- Requires exhaustive testing!!!
- Improved selection speed and re-rendering
- Upon infinite scroll, new files will be added …

task/TUI-205 -- files listing select all

---

src/tapis-app/Files/_components/Toolbar/Toolbar.test.tsx
src/tapis-app/Files/_components/Toolbar/Toolbar.tsx

Unit tests for toolbar
- [TUI-213](https://github.com/tapis-project/tapis-ui/issues/213)
- Unit tests for toolbar
- Always enable Add Folder and Upload regardless of file selection state
- Pass additional props to ToolbarButtons
1. npm run test

task/TUI-213 - Unit tests for Toolbar

---

src/tapis-api/utils/errorDecoder.ts

Add error type casting to error decoder to avoid unknow type errors with typescript 4.4.X
- [TUI-231](https://github.com/tapis-project/tapis-ui/issues/231)
Add type casting to errors
1.

TUI 231 - Update error decoder with error types

---

src/tapis-app/Files/_components/Toolbar/CopyMoveModal/CopyMoveModal.module.scss
src/tapis-app/Files/_components/Toolbar/CopyMoveModal/CopyMoveModal.tsx
src/tapis-app/Files/_components/Toolbar/Toolbar.tsx
src/tapis-app/Files/_components/Toolbar/TransferModal/TransferModal.tsx
src/tapis-app/Files/_components/Toolbar/UploadModal/UploadModal.tsx
src/tapis-ui/components/files/FileListing/FileListing.tsx

Punch-list items to finish up Files milestone
- [TUI-227](https://github.com/tapis-project/tapis-ui/issues/227)
- master select unchecks when there are no selected files
- file transfers listings update with interval timer
- disabled Permissions modal
- selected files state persist after move/copy operation
- implemented file ops reducer pattern from uploads
- dynamic naming of move copy modal
1. Trigger move/copy modal to see the headers, buttons, etc. dynamically set based on file operation
2. Try to trigger permissions modal (you can't; disabled)
3. Use master select to select all files, then click the checkbox of one or more files. Master select will uncheck.

Task/TUI 227  nathandf punchlist

---

src/tapis-ui/components/jobs/JobLauncher/steps/FileInputs.tsx

JobFileInputs step Formik initialValue should not generate new values, but instead should use what is currently in the useJobLauncher hook
- [TUI-282](https://github.com/tapis-project/tapis-ui/issues/282)
1. Test FileInputs steps (adding, removing, changing values, navigating past it and then returning to it)

task/TUI-282 -- initial values should be based on current job value

---

src/tapis-ui/_common/FieldWrapperFormik/fields/FormikTapisFile.tsx
src/tapis-ui/components/files/FileSelectModal/FileSelectModal.tsx
src/tapis-ui/components/jobs/JobLauncher/JobLauncherWizard.tsx
src/tapis-ui/components/jobs/JobLauncher/components/FormikJobStepWrapper.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/Archive.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/JobStart.tsx

Add archiving options and description
- [TUI-294](https://github.com/tapis-project/tapis-ui/issues/294)
- Add description to job start step
- Change Archive Filter step to be Archiving Options, include archiveSystemId, etc.
- Modify FormikTapisInput to allow directory only selection
- Modify FileSelectModal to allow directory only selection
1. Test Job Start step by modifying description
2. Test Archiving options by selecting a system and then a directory within that system

task/TUI-294 -- misc fields

---

src/tapis-api/utils/jobDefaults.ts
src/tapis-api/utils/jobExecSystem.test.ts
src/tapis-api/utils/jobExecSystem.ts
src/tapis-api/utils/jobRequiredFields.ts
src/tapis-ui/_common/FieldWrapperFormik/fields/FormikSelect.tsx
src/tapis-ui/_common/FieldWrapperFormik/fields/formikPatch.ts
src/tapis-ui/components/jobs/JobLauncher/JobLauncherWizard.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/ExecOptions.test.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/ExecOptions.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/JobSubmit.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/utils.ts

Allow undefined values for exec system and exec system logical queue, so that app or system defaults can be used
- [TUI-314](https://github.com/tapis-project/tapis-ui/issues/314)
- Add formikPatch that allows setting values in to undefined in FormikSelect
- Allow undefined defaults for execSystemId and execSystemLogicalQueue, so that they will fall back to the app specified exec system
- Add utility functions for computing exec system and queue defaults
1. Test with both bsf v1 and NoExecSystem apps
2. Try using undefined defaults and seeing if the jobs can be submitted with undefined values
3. Try switching back and forth between fork and batch jobs (if the job is switched to batch and the previously selected system has no queues, the value should return to being undefined)
If approved, …

task/TUI-314 -- allow undefined values for app/system defaults

---

src/tapis-api/utils/jobDefaults.ts
src/tapis-api/utils/jobExecSystem.test.ts
src/tapis-api/utils/jobExecSystem.ts
src/tapis-api/utils/jobRequiredFields.ts
src/tapis-ui/_common/FieldWrapperFormik/fields/FormikSelect.tsx
src/tapis-ui/_common/FieldWrapperFormik/fields/formikPatch.ts
src/tapis-ui/components/jobs/JobLauncher/JobLauncherWizard.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/ExecOptions.test.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/ExecOptions.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/JobSubmit.tsx
src/tapis-ui/components/jobs/JobLauncher/steps/utils.ts

- Revise Exec System Option behavior when selecting batch or fork job types
- [TUI-314](https://github.com/tapis-project/tapis-ui/issues/314)
- Exec system or queue selection changes values after form validation (was previously setting value upon dropdown selection, which does not follow form validation life cycle in other steps)
- Upon selecting fork jobs, hide batch queue options and allow selection of any exec system
- Upon selecting batch jobs, filter selectable systems for those with batch logical queues
- Allow undefined values for execSystemId, execSystemLogicalQueue, jobType that fall back upon defaults based on documented TAPIS logic
- Utility functions for computing default values, validating exec system selections
1. Try changing exec system job types
2. Try selecting different …

task/TUI-314 -- filter exec systems when selecting batch jobType

---

package-lock.json
package.json

- [TUI-359](https://github.com/tapis-project/tapis-ui/issues/359)
- update `tapis-typescript` version to `0.0.27` to include  ML Hub models api
1.

updated tapis-typescript version

---

src/tapis-app/Dashboard/_components/Dashboard/Dashboard.tsx
src/tapis-app/MlHub/Dashboard/Dashboard.module.scss
src/tapis-app/MlHub/Dashboard/Dashboard.tsx
src/tapis-app/MlHub/Dashboard/index.ts
src/tapis-app/MlHub/_Layout/Layout.module.scss
src/tapis-app/MlHub/_Layout/Layout.tsx
src/tapis-app/MlHub/_Layout/index.ts
src/tapis-app/MlHub/_Router/Router.tsx
src/tapis-app/MlHub/_Router/index.ts
src/tapis-app/MlHub/_components/Menu/Menu.module.scss
src/tapis-app/MlHub/_components/Menu/Menu.tsx
src/tapis-app/MlHub/_components/Menu/index.ts
src/tapis-app/MlHub/_components/index.ts
src/tapis-app/MlHub/index.ts
src/tapis-app/_Router/Router.tsx

Dashboard for ML Hub
- [TUI-365](https://github.com/tapis-project/tapis-ui/issues/365)
1. ML Hub card on main dashboard page.
2. Dashboard page for ML Hub with cards for:
-  Models Hub
-  Datasets Hub
-  Inference Server
-  Training Engine
1.
Added datasets hub as placeholder since we had discussion about it during [Tapis AI Integration meeting](https://docs.google.com/document/d/1v_QEdjdtvjdqnVcrAK5CGLCeE3zngYZLwIIkoykcDu8/edit?pli=1#heading=h.dull1y59dslr)

TUI 365  Dashboard for ML Hub

---

lib/tapisui-hooks/src/ml-hub/datasets/basePath.ts
lib/tapisui-hooks/src/ml-hub/datasets/useCardDetails.ts
lib/tapisui-hooks/src/ml-hub/datasets/useDetails.ts
lib/tapisui-hooks/src/ml-hub/datasets/useList.ts
lib/tapisui-hooks/src/ml-hub/datasets/useListByAuthor.ts
lib/tapisui-hooks/src/ml-hub/datasets/useListByLanguage.ts
lib/tapisui-hooks/src/ml-hub/datasets/useListByQuery.ts
lib/tapisui-hooks/src/ml-hub/datasets/useListBySizeCategory.ts
lib/tapisui-hooks/src/ml-hub/datasets/useListByTask.ts
lib/tapisui-hooks/src/ml-hub/datasets/useListDownloadLinks.ts
lib/tapisui-hooks/src/ml-hub/index.ts
lib/tapisui-hooks/src/ml-hub/models/basePath.ts
lib/tapisui-hooks/src/ml-hub/models/inference/useInferenceServerDetails.ts
lib/tapisui-hooks/src/ml-hub/models/useDetails.ts
lib/tapisui-hooks/src/ml-hub/models/useList.ts
lib/tapisui-hooks/src/ml-hub/models/useListByAuthor.ts
lib/tapisui-hooks/src/ml-hub/models/useListByDataset.ts
lib/tapisui-hooks/src/ml-hub/models/useListByLanguage.ts
lib/tapisui-hooks/src/ml-hub/models/useListByLibrary.ts
lib/tapisui-hooks/src/ml-hub/models/useListByQuery.ts
lib/tapisui-hooks/src/ml-hub/models/useListByTask.ts
lib/tapisui-hooks/src/ml-hub/models/useListDownloadLinks.ts

- changed implementation from a hard-coded `basePath` to resolving basePath implicitly
- TUI #402
1. @dhannywi will test locally if the new implementation works as expected once @NotChristianGarcia register ML Hub's Hub pod on NGINX proxy

ML Hub - resolve base path implicitly

---

src/app/MlHub/Models/ModelDetails.module.scss
src/app/MlHub/Models/ModelDetails.tsx

Task/t UI 374 download model functionality

---

src/app/Systems/_components/SystemToolbar/CreateSystemModal/CreateSystemModal.tsx
src/app/Systems/_components/SystemToolbar/CreateSystemModal/Settings/AdvancedSettings.tsx
src/app/Workflows/_components/Toolbar/CreateArchiveModal/CreateArchiveModal.tsx

Bugfix/t UI 323 default item create archive modal

---

packages/tapisui-api/src/utils/errorDecoder.test.ts
packages/tapisui-api/src/utils/errorDecoder.ts
packages/tapisui-common/src/wrappers/QueryWrapper/QueryWrapper.tsx
src/app/Systems/_Router/Router.tsx
src/app/Systems/_components/SystemsNav/SystemsNav.module.scss
src/app/Systems/_components/SystemsNav/SystemsNav.tsx

Add scroll functionality to systems toolbar, remove system limit of 100, lock systems toolbar in place so user can scroll systems while keeping current system definition, fix error decoder. 
1.

Task/t UI 441 render permissions error for systems not owned

---

packages/icicle-tapisui-extension/src/index.ts
packages/icicle-tapisui-extension/src/pages/Harvest/Harvest.tsx
packages/icicle-tapisui-extension/src/pages/Harvest/index.ts
packages/icicle-tapisui-extension/src/pages/index.tsx

Adds ICICLE extension for Harvest
N/A
Create new extension that connects to Harvest created by the ICICLE Digital Agriculture team

add harvest extension
